### PR TITLE
Extracts switchboard/api/middleware into cfhttp/middleware

### PR DESCRIPTION
**Pull request by chendrix**
We have extracted code from switchboard, while also cleaning up the implementations and backfilling tests.

I fully expect to have to change things as we talk through this PR.

Signed-off-by: Aaron Hurley <ahurley@pivotal.io>

### CODE REVIEW

**Comment by andrew-edgar** [comment]
Hi Chris and Aaron,

We pulled this code in and it failed to compile due to the fact that the lager library moved to code.cloudfoundry.org can you please update the PR with the new import paths.

Otherwise this looks good and we will be able to merge it in shortly.

Thanks,

Andrew & Anoop

**Comment by ematpl** [comment]
Thanks again, @chendrix and @aaronshurley. Are you aware of other CF teams that might also benefit from consolidating these middleware components in one common repository?

Best,
Eric

**Comment by chendrix** [comment]
Unsure, but any of our teams which create API servers will probably have some form of this written ad-hoc or copied from some root source.

**Comment by chendrix** [comment]
@andrew-edgar done :)

**Comment by andrew-edgar** [comment]
One question on the HTTPSEnforcer.  Why do we need a flag?  When would somebody use the HTTPSEnforcer but NOT enforce https?  I would think remove that flag and the test associated with the flag being false.

Andrew Edgar

**Comment by jvshahid** [comment]
bump

**Comment by bdshroyer** [comment]
Hi @chendrix,

Any further updates on this?


Thanks,
Brandon
CF Diego Development

**Comment by chendrix** [comment]
You might as well close the PR.

This is low priority for us and I don't have the energy to figure out what exactly we want to share.

Sincerely,
Christopher Hendrix

**Pull request closed without merging**
